### ISSUE TITLE
Set default temperature for SUmmer / Winter

### ISSUE THREAD

**Issue by kennguyen0303** [kennguyen0303/SOEN343_Delivery-3-#25]
Set the default temperatures for winter and summer time, when the home is in away mode.  This applies to all zones in a home.  These parameters are set in the SHH tab.

A few notes:

1. There are two arrays storing the months corresponding to Summer or Winter time. These two arrays will be stored in GlobalVariable.js

2. Need to check the simulator time. If the current month is inside array for Summer_month, the simulator should run in Summer mode then. The same thing applies for Winter mode.

3. GUI for setting temperatures are located on SHH tab

**Comment by NathanZiri** [comment]
fixed in commit 4290a6a
