### ISSUE TITLE
#23 #24 should be for desired temperature rather than the real/current temperature of a room

### ISSUE THREAD

**Issue by kennguyen0303** [kennguyen0303/SOEN343_Delivery-3-#31]
I think the 2 functions should be used for the desired temperature of a room rather than the real temperature since the real temperature should be maintained by the HVAC system. 

Your two buttons are working with the real temperature of a room right now. A new variable (also its setter and getter) for the desired temperature of a room has just been created. Please have a look and update your functions.

![image](https://user-images.githubusercontent.com/60043570/101241572-49d3b300-36c5-11eb-903d-abcbf5805acd.png)

p/s: 'main" is the most up-to-date and complete branch. Please create a new branch from "main" to debug the problem.

**Comment by NathanZiri** [comment]
fixed in commit a07698b
