### ISSUE TITLE
create classes for SHH subsystem

### ISSUE THREAD

**Issue by Alex-DSJ** [kennguyen0303/SOEN343_Delivery-3-#6]
contain the necessary attrbutes to store temperature imformation;
offer necessary functions to manipulate the attributes;
offer the methods to implement observer pattern;

**Comment by kennguyen0303** [comment]
So, have you implemented the observer pattern for the SHH yet ?

**Comment by Alex-DSJ** [comment]
> So, have you implemented the observer pattern for the SHH yet ?

no, "offer the methods to implement observer pattern" means I will mark in the method where the observer can be placed.

**Comment by Alex-DSJ** [comment]
all classes been created.
and the place for observer.notifyAll() method
![place for observer](https://user-images.githubusercontent.com/55929166/101143983-ad86af00-35e5-11eb-9088-a6cb07c4d706.png)
